### ISSUE TITLE
Major refactor related to target checkout and uninstallation

### ISSUE THREAD

**Issue by ar13pit** [tue-robotics/tue-env#406]
- [ ] Check and display all missing targets first (#403)
- [ ] Remove dead symlinks and repos (#401)
- [ ] Fix `target_setup.bash` for uninstalled targets (#369)
- [ ] Fix overruling of robocup branch by version/branch (#399)
- [ ] Add repo checkout parameter to env (#402)
